export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
  export default function GroupLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <div>
        <header style={{backgroundColor:'orange', padding:'5rem'}}>Header</header>
        <div style={{padding:'2rem'}}>{children}</div>
        <footer style={{backgroundColor:'pink', padding:'5rem'}}>Footer</footer>

      </div>
    )
  }
  